const weather = [
  {
    id: 1,
    temperature: 74,
    time: "07:00",
    date: "2022-08-13",
    current_weather: "Sunny",
    uv_index: 5,
    wind_speed: 12,
    humidity: 28,
    description: "lorem ipsum",
    icon: "url",
  },
  {
    id: 2,
    temperature: 44,
    time: "01:00",
    date: "2022-08-13",
    current_weather: "Snowing",
    uv_index: 5,
    wind_speed: 12,
    humidity: 28,
    description: "lorem ipsum",
    icon: "url",
  },
  {
    id: 3,
    temperature: 60,
    time: "07:09",
    date: "2022-08-13",
    current_weather: "Windy",
    uv_index: 5,
    wind_speed: 12,
    humidity: 28,
    description: "lorem ipsum",
    icon: "url",
  },
  {
    id: 4,
    temperature: 37,
    time: "04:59",
    date: "2022-08-13",
    current_weather: "Tornado",
    uv_index: 5,
    wind_speed: 12,
    humidity: 28,
    description: "lorem ipsum",
    icon: "url",
  },
  {
    id: 5,
    temperature: 90,
    time: "08:09",
    date: "2022-08-13",
    current_weather: "Volcano Eruption",
    uv_index: 5,
    wind_speed: 12,
    humidity: 28,
    description: "lorem ipsum",
    icon: "url",
  },
  {
    id: 6,
    temperature: 80,
    time: "01:09",
    date: "2022-08-13",
    current_weather: "Earthquake",
    uv_index: 5,
    wind_speed: 12,
    humidity: 28,
    description: "lorem ipsum",
    icon: "url",
  },
  {
    id: 7,
    temperature: 101,
    time: "07:56",
    date: "2022-08-13",
    current_weather: "Hailing",
    uv_index: 5,
    wind_speed: 12,
    humidity: 28,
    description: "lorem ipsum",
    icon: "url",
  },
  {
    id: 8,
    temperature: 65,
    time: "05:09",
    date: "2022-08-13",
    current_weather: "Normal",
    uv_index: 5,
    wind_speed: 12,
    humidity: 28,
    description: "lorem ipsum",
    icon: "url",
  },
  {
    id: 9,
    temperature: 43,
    time: "07:09",
    date: "2022-08-13",
    current_weather: "Storm",
    uv_index: 5,
    wind_speed: 12,
    humidity: 28,
    description: "lorem ipsum",
    icon: "url",
  },
  {
    id: 10,
    temperature: 99,
    time: "11:09",
    date: "2022-08-13",
    current_weather: "Wild Fire",
    uv_index: 5,
    wind_speed: 12,
    humidity: 28,
    description: "lorem ipsum",
    icon: "url",
  },
];

export default weather;
